### ISSUE TITLE
Rotate Tor IPs

### ISSUE THREAD

**Issue by edudemy** [HeitorG/nipe#4]
Hello @HeitorG 

Would like to rotate Tor IPs periodically, like say minute or hour
Is it possible with nipe

**Comment by HeitorG** [comment]
Hi @edudemy, you want to use Tor to have a IP "random"?

**Comment by naijim** [comment]
I think he meant rotating socks proxy

**Comment by HeitorG** [comment]
Every time the "start" is given, a new IP is loaded. You can do a "bash script" to the "start" at a certain time interval. :smile:

**Comment by HeitorG** [comment]
The next version of Nipe will have it, 
it will generate a different IP every 5 minutes.
Thanks for suggestion!
